import { Inter, Itim } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "./components/SessionProvider";
import "./globals.css";
import * as React from "react";
import { NextUiProviders } from "./Nexuiprovider";
import Navbar from "./components/Navbar";
const itim = Itim({ weight: '400', subsets: ["thai"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={itim.className}>
        <NextUiProviders>
          <SessionProvider session={session}>
            <Navbar></Navbar>
            {children}
          </SessionProvider>
        </NextUiProviders>
      </body>
    </html>
  );
}
